### ISSUE TITLE
100% stmts and branches

### ISSUE THREAD

**Issue by u9520107** [trungfinity/istanbul-traceur#4]
Oddly when I try this module to instrument the es6 source. The report always report 100% for statements, branches, and lines. Only functions coverage seem to differ.

I get 100% coverage on those areas simply by requiring the tested modules without using them to do anything.

**Comment by albertorestifo** [comment]
:+1:  me too

**Comment by andre1810** [comment]
me too

**Comment by u9520107** [comment]
Project appears to be dead or moved.
